### ISSUE TITLE
Current plan for impress.js: Set up the repository

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [impress/impress.js#512]
Here are some tasks that we will probably be doing in the incoming weeks to setup impress.js in a state where everything is focused well documented for future contributors and users of impress.js.

**Clean up**

The tasks here take in consideration [my comment in the state of the project](https://github.com/impress/impress.js/issues/435#issuecomment-177916049) and @bartaz [suggestions](https://github.com/impress/impress.js/issues/435#issuecomment-178468261) in the same thread.

- [x] Check all Pull Requests to find the ones where the OP is still interested in keeping track of it with the following message:

> Hi \<name of the poster>, in an effort to clear up older issues/PRs we are pinging back to know if you are still tracking this request.

> To give a little bit of context, recently [a decision was made in the project](https://github.com/impress/impress.js/issues/435#issuecomment-177602861) to make the development more active and the first task is to clear up older PRs like this one to see if [the OP](https://medium.com/@fagnerbrack/what-does-op-means-on-github-8db958b604af) is still interested in keep it going.

If the OP does not want it anymore, just close it or create an issue for tracking purposes.

- [x] Check all issues and close duplicates. If one issue refers to more than one feature, create one issue for each. (X-reference everything with github linking so we can get the whole context from any endpoint.). If the issue is solved, close it.

- [x] Review all PRs and close the ones that doesn't make sense or the ones that are doing more than one thing after acknowledgement of the OP (or 1 week of no response).

- [x] Review all issues and close the ones that doesn't make sense after acknowledgement of the OP (or 1 week after no response).

At this point we will have only the essential issues/PRs open, all the others will be closed.

**Contributing**

- [x] Create a CONTRIBUTING.md file to guide new contributions (or filter existing ones). [Here is a nice example](https://github.com/js-cookie/js-cookie/blob/3f2b5e6884407c54b391483f39ddcd4c70f9243c/CONTRIBUTING.md). Add to the "WANT TO CONTRIBUTE?" section of the README.

- [x] Review the changelogs (Fill the changelog in the "Releases" page for every version released so far)

**Documentation**

- [x] Clear the wiki, removing projects that are no longer maintained and useless pages (Fixed on https://github.com/impress/impress.js/issues/524#issuecomment-188218591).
- [x] Document the currently supported API in the README (#563).
- [x] Document the support only for evergreen browsers that support CSS 3D transform (easier than always having to update the support) (#565)

**Release**

- [x] Create a new minor release
- [x] Release on npm (#426)

... After all that, I will create a new issue with tasks regarding the open PRs and what we will be doing next for the future of impress.js!

ping @impress/mergers

**Comment by Pierstoval** [comment]
Totally agree with this :+1: 

What I'd recommend is to create a very basic `CONTRIBUTING.md` file that would simply ask to read this issue so new contributors only refer bugs in their new tickets and no new features. Maybe then some contributors might help in the proces of cleaning the repo. What do you think?

**Comment by FagnerMartinsBrack** [comment]
That makes sense while we are at the cleaning process, although it doesn't seems worth ignoring feature proposals.

**Comment by henrikingo** [comment]
For the contributing file, I would add:

* While we may not have 100% test coverage in the near future, it is a pre-requisite for considering any pull request that the code being touched is covered by tests. If this is not the case, you're invited to start by adding such tests (testing the current code) after which you can propose your fix or new feature.
* Pull requests should of course add their own tests testing the new or changed functionality, or in case of a bug fix, protecting against regressions.

**Comment by FagnerMartinsBrack** [comment]
Good idea.

**Comment by FagnerMartinsBrack** [comment]
@henrikingo 

> For the contributing file, I would add:

> * While we may not have 100% test coverage in the near future, it is a pre-requisite for considering any pull request that the code being touched is covered by tests. If this is not the case, you're invited to start by adding such tests (testing the current code) after which you can propose your fix or new feature.
> * Pull requests should of course add their own tests testing the new or changed functionality, or in case of a bug fix, protecting against regressions.

I have created the [initial version of the contributing file](https://github.com/impress/impress.js/pull/520). For the moment it reflects the master branch, it can be improved later, feel free to review :+1:

**Comment by Pierstoval** [comment]
I think we should leave this issue open until the project gets some cleanup for we can remember that contributing guidelines should be changed when the API changes and gets better :)

**Comment by FagnerMartinsBrack** [comment]
@Pierstoval Are you suggesting to keep this issue open even after the tasks in the description are completed?

**Comment by Pierstoval** [comment]
Oh no, actually I was just talking about the `contributing` file, nevermind I think I got lost in the huge amount of issues :smile:

**Comment by FagnerMartinsBrack** [comment]
> Oh no, actually I was just talking about the contributing file, nevermind I think I got lost in the huge amount of issues :smile:

Oh ok :)

**Comment by FagnerMartinsBrack** [comment]
Just finished triaging all PRs.

* The relevant ones are open and marked with the label `backlog`.
* I was able to reduce from ~100 PRs to just 13 of same value.
* Can only start reviewing once we have a proper suite of tests or plugin API (in case of some of those open PRs)

**Comment by FagnerMartinsBrack** [comment]
Added a new task in the "Documentation" section:

* Clean up the CHANGELOG.md file to be consistent with the releases page

**Comment by FagnerMartinsBrack** [comment]
I have finished adding all releases in the [Releases page](https://github.com/impress/impress.js/releases) along with their equivalent tags and link to PRs/commits.

I have used the [CHANGELOG.md](https://github.com/impress/impress.js/blob/5bdd53432161f5d67664cc4f4cd01c0c13f74d91/CHANGELOG.md) file as a reference to the content to the changelog. Some stuff might have been added that are not in the changelog but make bigger changes to the implicit public contract.

The following show all changes between versions in case anyone wants to verify (If possible, I encourage to do so):

* [0.2...0.3](https://github.com/impress/impress.js/compare/0.2...0.3)
* [0.3...0.4](https://github.com/impress/impress.js/compare/0.3...0.4)
* [0.4...0.4.1](https://github.com/impress/impress.js/compare/0.4...0.4.1)
* [0.4.1...0.5](https://github.com/impress/impress.js/compare/0.4.1...0.5)
* [0.5...0.5.1](https://github.com/impress/impress.js/compare/0.5...0.5.1)
* [0.5.1...0.5.2](https://github.com/impress/impress.js/compare/0.5.1...0.5.2)
* [0.5.2...0.5.3](https://github.com/impress/impress.js/compare/0.5.2...0.5.3)

I will be creating a draft of the next 0.6.0 version that will be available only to collaborators.

**Comment by FagnerMartinsBrack** [comment]
impress.js 0.6.0 have been released in Github and npm:

* https://www.npmjs.com/package/impress.js
* https://github.com/impress/impress.js/releases/tag/0.6.0
